### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by Mellnik** [urShadow/StringObfuscator#1]
Compiling your Hello World example with GCC 5.4.
`dev@ubuntuserver:~# g++ -m64 -std=c++1y -O2 strobfs.cpp -o strobfs && strip strobfs && strings strobfs | grep Hello`
`Hello, World!`

Still shows the string "Hello, World!" when dumped with `strings` command.

What am I doing wrong?

**Comment by urShadow** [comment]
`g++ -std=c++14 -O2 main.cpp -o test`
All right. Version 6.1.1.

**Comment by juhalaukkanen** [comment]
Works but highly depends on compiler and parameters.

For example my tests on clang++ 3.6

clang++-3.6 test.cpp --std=c++14 -> all strings visible
clang++-3.6 test.cpp --std=c++14 -O2 -> some string paritially obfuscated
clang++-3.6 test.cpp --std=c++14 -O3 -> "Hello, World!" string completely obfuscated, but still some tests strings visible completely or partially.

Maybe make it less dependent on compiler and parameters?
